add test for Reg and Auth
dtyta/cypressHW pull request #1
Opened 2023-05-28 18:11 UTC by dtyta

2023-05-29 07:17 UTC, SanitarskyiDmytro requested changes
тести на реєстрацію та авторизацію потрібно розділити на окремі

2023-05-29 08:35 UTC, dtyta commented
@SanitarskiyDima  розділив тести на реєстрацію та авторизацію

2023-05-29 12:23 UTC, SanitarskyiDmytro requested changes

2023-05-29 12:23 UTC, SanitarskyiDmytro commented on cypress/e2e/regAndAuth.cy.js
>        cy.get('[class="btn btn-orange pull-right lock-on-click"]').click();
Цей тест працює як треба, тільки в кінці потрібно перевіряти, чи зʼявився месседж про успішну реєстрацію)
Бо зараз по факту він не проходить, тому що такий юзер вже зареєстрований

2023-05-29 12:38 UTC, dtyta commented on cypress/e2e/regAndAuth.cy.js
>        cy.get('[class="btn btn-orange pull-right lock-on-click"]').click();
Зламав тест начальнік)

2023-05-29 12:38 UTC, dtyta commented
@SanitarskiyDima  додав перевірку до реєстрації

2023-05-31 10:11 UTC, dtyta commented
@SanitarskiyDima додав тест на оформлення замовлення

2023-05-31 11:00 UTC, DmytroSanitarskyi approved these changes

2023-05-31 12:00 UTC, merged